const products = [
    {
    id: 1,
    name: "Smartphone X12",
    prevPrice: 799,
    currPrice: 699,
    image: "https://tse3.mm.bing.net/th?id=OIP.CRBBGZZzyJGhWrt1kCbRQQHaHa&pid=Api&P=0&h=180",
    },
    {
    id: 2,
    name: "Laptop Pro 15",
    prevPrice: 1399,
    currPrice: 1299,
    image: "https://c.pxhere.com/photos/21/73/iphone_smartphone_phone_mobile_phone_technology_touch_screen_mobile-1091005.jpg!d",
    },
    {
    id: 3,
    name: "Wireless Earbuds Z",
    prevPrice: 199,
    currPrice: 149,
    image: "https://purepng.com/public/uploads/large/samsung-phone-270.png",
    },
    {
    id: 4,
    name: 'Smart TV 50"',
    prevPrice: 899,
    currPrice: 799,
    image: "https://freepngimg.com/thumb/samsung_mobile_phone/11-2-samsung-mobile-phone-png-pic.png",
    },
    {
    id: 5,
    name: "Gaming Console 5",
    prevPrice: 599,
    currPrice: 499,
    image: "https://www.pngarts.com/files/3/Smartphone-Mobile-PNG-Image-Background.png",
    },
    {
    id: 6,
    name: "Bluetooth Speaker Mini",
    prevPrice: 129,
    currPrice: 99,
    image: "http://www.pngall.com/wp-content/uploads/2016/06/Samsung-Mobile-Phone-Free-Download-PNG.png",
    },
    {
    id: 7,
    name: "4K Action Camera",
    prevPrice: 349,
    currPrice: 299,
    image: "https://www.pngplay.com/wp-content/uploads/12/Smartphone-PNG-Free-File-Download.png",
    },
    {
    id: 8,
    name: "Smartwatch Elite",
    prevPrice: 249,
    currPrice: 199,
    image: "https://www.dhresource.com/0x0s/f2-albu-g17-M01-AC-F0-rBVa4l-04CSAEsGhAANodbh1tFc856.jpg/original-realme-q2-5g-mobile-phone-4gb-ram.jpg",
    },
    {
    id: 9,
    name: "Gaming Headset X",
    prevPrice: 129,
    currPrice: 89,
    image: "https://www.91-img.com/pictures/152686-v1-vivo-v25-5g-256gb-mobile-phone-hres-7.jpg",
    },
    {
    id: 10,
    name: "External SSD 1TB",
    prevPrice: 199,
    currPrice: 149,
    image: "https://www.pngplay.com/wp-content/uploads/12/Smartphone-PNG-Free-File-Download.png",
    },
    {
    id: 11,
    name: "Drone Phantom",
    prevPrice: 999,
    currPrice: 899,
    image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6202/6202341_rd.jpg",
    },
    {
    id: 12,
    name: "Digital Camera HD",
    prevPrice: 599,
    currPrice: 549,
    image: "https://m.media-amazon.com/images/I/61TLDQrtEOL.SL1500.jpg",
    },
    {
    id: 13,
    name: "Portable Charger 20k",
    prevPrice: 79,
    currPrice: 59,
    image: "https://clipart.info/images/ccovers/1503496384iphone-png-mobile-clipart.png",
    },
    {
    id: 14,
    name: "VR Headset Pro",
    prevPrice: 399,
    currPrice: 349,
    image: "https://www.pngall.com/wp-content/uploads/2016/06/Samsung-Mobile-Phone-Free-Download-PNG.png",
    },
    {
    id: 15,
    name: 'Tablet 10.1"',
    prevPrice: 449,
    currPrice: 399,
    image: "http://www.pngmart.com/files/7/Mobile-Phone-Transparent-PNG.png",
    },
    {
    id: 16,
    name: "Wireless Keyboard",
    prevPrice: 69,
    currPrice: 49,
    image: "https://images.priceoye.pk/apple-iphone-14-pakistan-priceoye-3j7db.jpg",
    },
    {
    id: 17,
    name: "Noise-Cancelling Headphones",
    prevPrice: 299,
    currPrice: 249,
    image: "https://i5.walmartimages.com/asr/1d90b3f4-0018-462f-808a-73f462ed0040_1.71fd072dba100123e752e6a37bf187b5.jpeg",
    },
    {
    id: 18,
    name: "Smart Home Speaker",
    prevPrice: 159,
    currPrice: 129,
    image: "https://freepngimg.com/thumb/samsung_mobile_phone/5-2-samsung-mobile-phone-png-hd.png",
    },
    {
    id: 19,
    name: "Projector 1080p",
    prevPrice: 649,
    currPrice: 599,
    image: "https://www.sahivalue.com/product-images/14+pro+max.jpg/293890000021697778/400x400",
    },
    {
    id: 20,
    name: "Fitness Tracker X",
    prevPrice: 99,
    currPrice: 79,
    image: "https://www.sahivalue.com/product-images/14+pro+max.jpg/293890000021697778/400x400",
    },
];

export default products;